project:
  version: v1
  status: created
  projectId: my-test-project
  displayName: my-test-project
  iam_permission:
    - role1
    - role2
    - role3
    - role4
  labels:
    cost: value
    team: value