project:
  version: v1
  owner: me
  project: foo
  foo: bar
  projectId: my-test-project
  displayName: my-test-project
  iam_permission:
    - role1
    - role2
    - role3
    - role4
  labels:
    cost: value
    team: value