name: Publish
on:
  push:
    tags:
      - 'v*' 
jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Build the binary wheel and source tarball
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
